# This is a basic workflow to help you get started with Actions

name: Run tests

# Controls when the action will run. 
on: push

jobs:
  tests:
    name: Automated tests
    # The type of runner that the job will run on
    runs-on: [ubuntu-latest, macos-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v2

      - name: Prepare modules
        run: npm install

      - name: Run tests
        run: npm test
